version: '3'
services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
  api:
    image: node:14
    ports:
      - "5000:5000"
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
